# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  farejador:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data
        run: |
          echo "Bla1"
      - name: Send to Telegram
        run: |
          echo "Bla" 
        
          
