name: CI

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  farejador:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data
        run: |
          echo "Bla1"
      - name: Send to Telegram
        run: |
          echo "Bla" 
        
          
